### ISSUE TITLE
Text Markup

### ISSUE THREAD

**Issue by KhairUnNisa10** [ammarazahid/test-9-may#1]
https://github.com/ammarazahid/test-9-may/blob/97ab7705b73c4dac35120244e687e1c4adac1aa5/index.html#L45-L49

https://github.com/ammarazahid/test-9-may/blob/97ab7705b73c4dac35120244e687e1c4adac1aa5/index.html#L62-L68

Every text should be in a tag, every text/content should be marked up in a tag to give the text/content its purpose, whether its a paragraph or a heading.. In this case its a paragraph, insert the p tag.

**Comment by ammarazahid** [comment]
done miss
