### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by KhairUnNisa10** [ammarazahid/test-9-may#3]
Insert logo in the head tag, to make it complete.

**Comment by ammarazahid** [comment]
mam knsa logo kindly btaden...mjhe nai smjh arahi

**Comment by KhairUnNisa10** [comment]
You can insert any random logo no specific needed.

**Comment by ammarazahid** [comment]
mam wo logo panda ki jaga add krna hai naw??

**Comment by KhairUnNisa10** [comment]
Yes, and remove the borders from the logo. And change the logo alignment. Its at the left on the top.

**Comment by ammarazahid** [comment]
mam mjh se nahi ho raha ye
