### ISSUE TITLE
Margin

### ISSUE THREAD

**Issue by KhairUnNisa10** [ammarazahid/test-9-may#4]
Do not use margin this much to give the page layouts and alignments to sections. Pages layout can be made using, flex, float etc to give them layout and alignments.

**Comment by ammarazahid** [comment]
okay mam

**Comment by ammarazahid** [comment]
mam i m using flex but my nav bar is looking too bad they all are merge together.. no spaces there

**Comment by KhairUnNisa10** [comment]
It looks good now, just try more flex. And insert icon in the responsive.

**Comment by ammarazahid** [comment]
wo hamburger wala icon??
