### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by KhairUnNisa10** [ammarazahid/test-9-may#7]
![image](https://user-images.githubusercontent.com/49787331/57972770-66f84200-79b8-11e9-9517-c43b7ef49bbe.png)

In the above image is your mockup, you can see that there are two borders one is with full width and one is with half width, remove the one with the half its increasing the border width which doesn't look so good.

Also thee product details part, remove the white space from the left and make its alignment like the above and below paragraph.

**Comment by ammarazahid** [comment]
done#7
